pipeline {
    agent any
    tools { nodejs "Node" }
    parameters {
        string(name: 'EXECUTOR', defaultValue: '', description: 'Nombre de la persona que ejecuta la pipeline')
        string(name: 'MOTIVO', defaultValue: '', description: 'Motivo de la ejecución de la pipeline')
        string(name: 'CHAT_ID', defaultValue: '', description: 'Chat ID de Telegram para notificaciones')
    }

    environment {
        LINTER_RESULT = ''
        TEST_RESULT = ''
        BUILD_RESULT = ''
        README_UPDATE_RESULT = ''
        PUSH_RESULT = ''
        DEPLOY_RESULT = ''
        NOTIFICATION_RESULT = ''
        GIT_USERNAME = 'EluMancebo'
        GIT_PASSWORD = credentials('GITHUB_TOKEN_ID')
    }

    stages {
        stage('Linter') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/linter.sh'
                    LINTER_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/linter.sh', returnStdout: true).trim()
                    echo "Resultado del linter: ${LINTER_RESULT}"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/test.sh'
                    TEST_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/test.sh', returnStdout: true).trim()
                    echo "Resultado de los tests: ${TEST_RESULT}"
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/build.sh'
                    BUILD_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/build.sh', returnStdout: true).trim()
                    echo "Resultado del build: ${BUILD_RESULT}"
                }
            }
        }

        stage('Update_Readme') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/update_radme.sh'
                    README_UPDATE_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/update_radme.sh', returnStdout: true).trim()
                    echo "Resultado de la actualización del README: ${README_UPDATE_RESULT}"
                }
            }
        }

        stage('Push Changes') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/push_changes.sh'
                    PUSH_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/push_changes.sh', returnStdout: true).trim()
                    echo "Resultado del push: ${PUSH_RESULT}"
                }
            }
        }

        stage('Deploy to Vercel') {
            when {
                expression { return (LINTER_RESULT == "success" && TEST_RESULT == "success" && BUILD_RESULT == "success" && README_UPDATE_RESULT == "success") }
            }
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/deploy_to_vercel.sh'
                    DEPLOY_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/deploy_to_vercel.sh', returnStdout: true).trim()
                    echo "Resultado del deploy: ${DEPLOY_RESULT}"
                }
            }
        }

        stage('Notificación') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/notification.sh'
                    NOTIFICATION_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/notification.sh', returnStdout: true).trim()
                    echo "Resultado de la notificación: ${NOTIFICATION_RESULT}"
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline completada"
        }
        success {
            echo "Pipeline ejecutada correctamente"
        }
        failure {
            echo "La pipeline ha fallado"
        }
    }
}
