pipeline {
    agent any
    tools { nodejs "Node" }
    parameters {
        string(name: 'EXECUTOR', defaultValue: '', description: 'Nombre de la persona que ejecuta la pipeline')
        string(name: 'MOTIVO', defaultValue: '', description: 'Motivo de la ejecución de la pipeline')
        string(name: 'CHAT_ID', defaultValue: '', description: 'Chat ID de Telegram para notificaciones')
    }

    environment {
        LINTER_RESULT = ''
        TEST_RESULT = ''
        BUILD_RESULT = ''
        README_UPDATE_RESULT = ''
        DEPLOY_RESULT = ''
        NOTIFICATION_RESULT = ''
    }

    stages {
        stage('Linter') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/linter.sh'
                    LINTER_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/linter.sh', returnStdout: true).trim()
                    echo "Resultado del linter: ${LINTER_RESULT}"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/test.sh'
                    TEST_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/test.sh', returnStdout: true).trim()
                    echo "Resultado de los tests: ${TEST_RESULT}"
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/build.sh'
                    BUILD_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/build.sh', returnStdout: true).trim()
                    echo "Resultado del build: ${BUILD_RESULT}"
                }
            }
        }

        stage('Update_Readme') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/update_radme.sh'
                    README_UPDATE_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/update_radme.sh', returnStdout: true).trim()
                    echo "Resultado de la actualización del README: ${README_UPDATE_RESULT}"
                }
            }
        }

        stage('Push Changes') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'GITHUB_TOKEN_ID', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    script {
                        sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/push_changes.sh'
                        try {
                            sh """
                                jenkins-pipeline-project/jenkinsScripts/push_changes.sh '${params.EXECUTOR}' '${params.MOTIVO}'
                            """
                            echo "Push completado con éxito."
                        } catch (Exception e) {
                            echo "Error al hacer push de los cambios: ${e.message}"
                            error "Push fallido."
                        }
                    }
                }
            }
        }

        stage('Deploy to Vercel') {
            when {
                expression { 
                    echo "Debugging Variables for Deploy to Vercel:"
                    echo "LINTER_RESULT: ${LINTER_RESULT}"
                    echo "TEST_RESULT: ${TEST_RESULT}"
                    echo "BUILD_RESULT: ${BUILD_RESULT}"
                    echo "README_UPDATE_RESULT: ${README_UPDATE_RESULT}"
                    return (LINTER_RESULT == "Linter: success" && TEST_RESULT == "Test: success" && BUILD_RESULT == "Build: success" && README_UPDATE_RESULT == "Update_readme: success") 
                }
            }
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/deploy_to_vercel.sh'
                    DEPLOY_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/deploy_to_vercel.sh', returnStdout: true).trim()
                    echo "Resultado del deploy: ${DEPLOY_RESULT}"
                }
            }
        }

        stage('Notificación') {
            steps {
                withCredentials([
                    string(credentialsId: 'telegram_bot_token', variable: 'TELEGRAM_BOT_TOKEN'),
                    string(credentialsId: 'telegram_chat_id', variable: 'CHAT_ID')
                ]) {
                    script {
                        echo "Debugging Telegram Credentials:"
                        echo "TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}"
                        echo "CHAT_ID: ${CHAT_ID}"
                        sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/notification.sh'
                        try {
                            sh """
                                jenkins-pipeline-project/jenkinsScripts/notification.sh
                            """
                            echo "Notificación enviada con éxito."
                        } catch (Exception e) {
                            echo "Error al enviar la notificación: ${e.message}"
                            error "Notificación fallida."
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline completada"
        }
        success {
            echo "Pipeline ejecutada correctamente"
        }
        failure {
            echo "La pipeline ha fallado"
        }
    }
}
