pipeline {
    agent any
    tools {nodejs "Node"}
    parameters {
        string(name: 'EXECUTOR', defaultValue: '', description: 'Nombre de la persona que ejecuta la pipeline')
        string(name: 'MOTIVO', defaultValue: '', description: 'Motivo de la ejecución de la pipeline')
        string(name: 'CHAT_ID', defaultValue: '', description: 'Chat ID de Telegram para notificaciones')
    }

    environment {
        LINTER_RESULT = ''
        TEST_RESULT = ''
        BUILD_RESULT = ''
        README_UPDATE_RESULT = ''
        PUSH_RESULT = ''
        DEPLOY_RESULT = ''
        NOTIFICATION_RESULT = ''
    }

    stages {
        
        
        stage('Linter') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/linter.sh'
                    LINTER_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/linter.sh', returnStdout: true).trim()
                }
            }
        }

        
        stage('Test') {
            steps {
                script {
                     sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/test.sh'
                    TEST_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/test.sh', returnStdout: true).trim()
                }
            }
        }

        
        stage('Build') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/build.sh'
                    BUILD_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/build.sh', returnStdout: true).trim()
                }
            }
        }

        
        stage('Update_Readme') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/update_radme.sh'
                    README_UPDATE_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/update_radme.sh', returnStdout: true).trim()
                }
            }
        }

        
       stage('Push_Changes') {
    steps {
        withCredentials([usernamePassword(credentialsId: 'GITHUB_TOKEN_ID', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
            script {
                // Configurar la URL remota con las credenciales
                sh """
                    git remote set-url origin https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/EluMancebo/practica_final_jenkins.git
                """

                // Ejecutar el script para hacer el push
                sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/push_changes.sh'
                PUSH_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/push_changes.sh', returnStdout: true).trim()

                // Mostrar el resultado del push
                echo "Push result: ${PUSH_RESULT}"
            }
        }
    }
}



       
        stage('Deploy to Vercel') {
            when {
                expression { return (LINTER_RESULT == "success" && TEST_RESULT == "success" && BUILD_RESULT == "success" && README_UPDATE_RESULT == "success") }
            }
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/deploy_to_vercel.sh'
                    DEPLOY_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/deploy_to_vercel.sh', returnStdout: true).trim()
                }
            }
        }

        
        stage('Notificació') {
            steps {
                script {
                    sh 'chmod +x jenkins-pipeline-project/jenkinsScripts/notificacion.sh'
                    NOTIFICATION_RESULT = sh(script: 'jenkins-pipeline-project/jenkinsScripts/notificacion.sh', returnStdout: true).trim()
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline completada"
        }

        success {
            echo "Pipeline ejecutada correctamente"
        }

        failure {
            echo "La pipeline ha fallado"
        }
    }
}